name: carqr_clean
description: Car QR Clean Project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0

flutter:
  uses-material-design: true

  # Uncomment if you add images to assets/images/ folder
  # assets:
  #   - assets/images/
